### PR TITLE
Retail profile

### PR DESCRIPTION
**Pull request by pow-21**

### CODE REVIEW

**Comment by pow-21** [comment]
insight image

**Comment by pow-21** [comment]
retail listing fixes

**Review by pow-21 — COMMENTED** [review]
done

**Review by pow-21 — COMMENTED** [review]
Done

**Review by pow-21 — COMMENTED** [review]
Yes

**Review by pow-21 — COMMENTED** [review]
Done

**Review by kanhaiyakumarsha — APPROVED** [review]

**Pull request merged**
